# TravisCI configuration for onepix/wordpress-stubs-generator

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "8.1"
  - "8.2"
  - "8.3"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "composer validate --strict"

install:
  - "composer update"

script:
  - "vendor/bin/phpunit --verbose"
