# TravisCI configuration for php-stubs/generator

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "7.3"
  - "7.4"
  - "nightly"

jobs:
  allow_failures:
    - php: "nightly"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "composer validate --strict"

install:
  - "composer update"

script:
  - "vendor/bin/phpunit"
